export const Space = {
  None: "m-0",
  VerySmall: "m-1",
  VerySmallLeft: "ml-1",
  VerySmallRight: "mr-1",
  VerySmallTop: "mt-1",
  VerySmallBottom: "mb-1",
  Small: "m-2",
  SmallLeft: "ml-2",
  SmallRight: "mr-2",
  SmallTop: "mt-2",
  SmallBottom: "mb-2",
  Base: "m-3",
  BaseLeft: "ml-3",
  BaseRight: "mr-3",
  BaseTop: "mt-3",
  BaseBottom: "mb-3",
  Large: "m-4",
  LargeLeft: "ml-4",
  LargeRight: "mr-4",
  LargeTop: "mt-4",
  LargeBottom: "mb-4",
  VeryLarge: "m-5",
  VeryLargeLeft: "ml-5",
  VeryLargeRight: "mr-5",
  VeryLargeTop: "mt-5",
  VeryLargeBottom: "mb-5",
} as const

export type Space = (typeof Space)[keyof typeof Space]
